### ISSUE TITLE
Throwing exception when username and password for the mongodb is used

### ISSUE THREAD

**Issue by shreekantha** [malike/sso-auth#4]
I am using mongodb with credentials , so I added all the properties which are required to connect to secure mongodb.
After adding credentials into application.properties, it started throwing exceptions.
Below is the details of application.properties
security.basic.enabled=false

logging.level.=INFO

#Client
app.client.id=sso-auth-client
app.client.secret=mySecret

# MONGODB (MongoProperties)
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=pms_ait
spring.data.mongodb.username=pmsmongoadmin
spring.data.mongodb.password=pmsmongo@admin

**Comment by malike** [comment]
What's the exception?  And I think this is separate from the main point of this project.
