### ISSUE TITLE
issue when running the server

### ISSUE THREAD

**Issue by lahmer** [malike/sso-auth#5]
Hi, I followed the steps you specified, but when i try to get to the URL 

> http://localhost:8080/oauth/token?grant_type=password&username=user@awesome.com&password=cant_hack_this&client_id=sso-auth-client&client_secret=mySecret

I am getting the following error 
WARN 20126 --- [nio-8080-exec-5] o.s.web.servlet.PageNotFound             : Request method 'GET' not supported

**Comment by malike** [comment]
Yes because GET is not supported. Use POST.
