### ISSUE TITLE
Getting 405 Request method 'GET' not supported for path /oauth/token

### ISSUE THREAD

**Issue by DineshGuptaa** [malike/sso-auth#7]
Hi Malike,
I am newbie for spring security oauth2. I set up project & run the project using eclipse.but getting below issue when invoking URL. Please help.
 http://localhost:8080/oauth/token?grant_type=password&username=user@awesome.com&password=cant_hack_this&client_id=sso-auth-client&client_secret=mySecret
{
    "timestamp": 1503311563804,
    "status": 405,
    "error": "Method Not Allowed",
    "exception": "org.springframework.web.HttpRequestMethodNotSupportedException",
    "message": "Request method 'GET' not supported",
    "path": "/oauth/token"
}

**Comment by malike** [comment]
Hello @DineshGuptaa,

Glad to help. 

Kindly confirm if you're not testing the get token rest call on the auth-client microservice.
A
"status": 405,
"error": "Method Not Allowed",

most probably means http://localhost:8080/oauth/token could not be found.
